name: Generate strings
on: push
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep '_FUNC'
        env:
          FORMAT_FUNC: ${{ format('{1}, {0}.', 'world', 'hello') }}
          JOIN_FUNC: ${{ join(github.event.*.html_url, ', ') }}
